### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by benoit7866** [Karlheinzniebuhr/Simple-Freeradius-Admin#2]
Hi,

is there an example keys.py somewhere ? I couldn't find it in the repository

thanks in advance

**Comment by kamalpanhwar** [comment]
I am also getting same error keys.py what is format it ?

**Comment by Karlheinzniebuhr** [comment]
I just added an example file, could you modify it with your data and try again?

**Comment by kamalpanhwar** [comment]
Thank you, now still no success
admin_1   | Traceback (most recent call last):
admin_1   |   File "./app.py", line 1, in <module>
admin_1   |     from SimpleAdmin import app
admin_1   |   File "/usr/src/app/SimpleAdmin/__init__.py", line 3, in <module>
admin_1   |     from SimpleAdmin import keys
admin_1   | ImportError: cannot import name 'keys'

**Comment by q2dg** [comment]
...mmm....
